site_name: 'Le Vecchie Musiche e la nuova maniera di leggerle'
#repo_url: https://github.com/nicholascornia89/vecchiemusiche
#repo_name: 'GitHub'
site_author: Nicholas Cornia
#docs_dir: 'docs'
#site_dir: '../../generated/en'
nav:
  - Home: index.md
  - Ensemble: ensemble.md
  - Projects: projects.md
  - Archive: archive.md
  - Members: members.md
  - Support us: support_us.md
  - Contact us: contact_us.md

plugins:
  - search
  - optimize
  #- toggle-sidebar
  - tags
  #- autorefs
  - mkdocs-video
  - data
  #- live-edit
  #- meta-manager
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: nl
          name: Nederlands
          build: true
        - locale: it
          name: Italiano
          build: true
  #- redirects:
      #redirect_maps:
        #'https://www.vecchiemusiche.be/nl/projecten/missa-romantica-nl/': 'nl/projects/missa_romantica.md'



extra_css:
  #custom_dir: 'overrides'
  - assets/stylesheets/extra.css

theme:
  name: material
  custom_dir: overrides
  logo: assets/images/VM-icon-red.png
  favicon: assets/images/favicon.ico
  language: en
  icon:
#    previous: fontawesome/solid/angle-left
#    next: fontawesome/solid/angle-right

  font:
    text: Sorts Mill Goudy
  palette:
    scheme: default
    primary: custom
    accent: custom
    footer: custom

  features:
    - navigation.instant
    - search.share
    - navigation.footer
    - navigation.tabs
    - navigation.tabs.sticky

copyright: Copyright &copy; 2025 Le Vecchie Musiche

extra:
  social:
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@nicholascornia7593/playlists
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/profile.php?id=100063282096014
  generator: false
  alternate:
    #Switch to English
    - name: English
      link: /en/
      lang: en
    # Switch to Dutch
    - name: Nederlands
      link: /nl/
      lang: nl
    # Switch to Italian
    - name: Italiano
      link: /it/
      lang: it

    


markdown_extensions:
  - footnotes
  - tables
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences





